#+类型: 2204
#+主页: [[归档202204]]

* 周一 [[2022_04_25]] [[Apr 25th, 2022]]
** #今日鸡汤 #周记

人生其实任何时候都准备不好，意外总会不期而至。我们只能迎难而上。

** #今日文章 #周记

《无题》

上世纪 80 年代，古巴的伟大领袖卡斯特罗决定收拾美帝，将国內的强奸犯、杀人犯、偷窃犯、妓女、残疾人、精神病人等近 15 万“低入口”驱赶到公海，这些人如其所料一股脑涌向美帝。

山姆大叔被突然而来的难民懵了，最后决定在南部划一块无人沼泽地投递食物并建立简易安置房安置这比难民。

二十年后这里成为“中南美贸易金融之都！” —— 迈阿密，如今被瑞士联合银行评为美国最富裕城市和全球第五富裕城市。

世界从来没有“低端入口”，只有高端畜牲。


* 周二 [[2022_04_26]] [[Apr 26th, 2022]]
** #今日鸡汤 #周记

人生得一知己，足矣。

** #今日文章 #周记

《无题》

最近流行的金句是：西方制度不适合中国人民，却非常适合中国移民。

这句话跟我此前讲过的一句很像：中国人反对自己的国家变成西方的殖民地，但是却非常向往全家去美加澳这些西方殖民地生活。


* 周三 [[2022_04_27]] [[Apr 27th, 2022]]
** #今日鸡汤 #周记

王朔：“我曾经以为日子是过不完的，未来是完全不一样的。现在我就呆在自己的未来，我没有发现自己有什么真正的变化，我的梦想还像小时候一样遥远，唯一不同的是我已经不打算实现它了。”

** #今日文章 #周记

《为什么穷人大多都很自卑？‘》

主要是没搞清楚人生的真相。

大部分人不存在智商碾压。就四个字，熟能生巧。

你到高档的地方去多了，你就熟悉了那套规则，于是，大家就说你见过世面了，说你优雅！

你恋爱谈多了，把男人女人的那些个窍门摸清楚了，于是你就成了传说中的平平无奇恋爱小天才。你搞一个男的，你很慌，你搞了一百个，你再搞一百零一个，你看你还慌不慌?随便上手好不好？
都是概率问题。

一个人只要有机会试错，他就没可能一直是个 low 逼。

穷人的关键卡壳就卡在这里，没有试错的资格，于是，就各种技能看起来都不行，于是里面很大一部分人就开始自我质疑，我是不是没有条件好的人聪明？没有他们努力？

绝对是错误思路。

当你理清了人生的真正思路后，你就再也不会责怪你自己了，自卑也免了吧。

就这么一回事儿。


* 周四 [[2022_04_28]] [[Apr 28th, 2022]]
** #今日鸡汤 #周记 #名人名言

勇者愤怒，抽刃向更强者;怯者愤怒，却抽刃向更弱者。 —— 鲁迅《华盖集·杂感》

** #今日文章 #周记

《最好的感情》

不用每天缠绵，随时保持联系，我知道你不会走，你知道我不会变，相互惦记，各自忙碌，开心的时候有人分享，难过的时候有人陪伴。有话直说，有话明说，相处时不用防备，聊天时毫无顾忌，这大概就是蕞好的感情。

—— 《杨绛传》书在橱窗


* 周五 [[2022_04_29]] [[Apr 29th, 2022]]
** #今日鸡汤 #周记

IP 易改，智商难觅。

** #今日文章 #周记

《什么是法治》

“什么是法制，对于私权而言，只要法律没有禁止都是公民的权利;对于公权而言，只要法律没有授权都是被禁止的。在某些地方，一纸红头文件就可以跳过立法把一个行业整的鸡飞狗跳。” —— 罗翔


* 周六 [[2022_04_30]] [[Apr 30th, 2022]]
** #今日鸡汤 #周记

6

** #今日文章 #周记

6


* 周日 [[2022_05_01]] [[May 1st, 2022]]
** #今日鸡汤 #周记

7

** #今日文章 #周记

7

