#+类型: 2203
#+主页: [[归档202203]]

* 周一 [[2022_03_28]] [[Mar 28th, 2022]]
** #今日鸡汤 #周记

疫情是个照妖镜，上海终归是中国的，和其他任何的国内城市并无本质区别。

** #今日文章 #周记

《上海抗疫》  #上海疫情

上联：浦东决战愚人节
下联：浦西决战清明节
横批：欢欢喜喜劳动节


* 周二 [[2022_03_29]] [[Mar 29th, 2022]]
** #今日鸡汤 #周记

人以是非定立场，
奴以立场定是非，
兽以食物定立场，
魔以成败定是非。


** #今日文章 #周记

《上海疫情》 #上海疫情

1. 在某种程度上，上海这次的防控方式是一种非常有必要的尝试，而这种尝试也只能在上海这个过去两年的防疫优等生上进行（我想有不少人对这一点持不同看法，以你的看法为准）。

2. 为什么要进行尝试，因为 BA.2 传染性和致病力的变化，因为疫苗接种率的变化，因为过去的一些防疫方式造成的次生问题大家有目共睹。

尽管国内很多人对防疫方式存在争论，但是比较明确的一点是处于极端的人并不多，基本没有人会同意直接像一些国家那样全面放开，也基本没有人会同意严防死守到病毒灭绝，但是大家都不清楚的一点是，目前这样的防控方式究竟能持续多久，未来是否会有阶段性变化。

如果没人尝试，我们只能原地踏步。实际上在过去面临各种传染病时，人类总是在不断地试错，有句话叫做“站在巨人的肩膀上”，你今天看到各种各样成功的防疫方式，背后都是大量的尝试，甚至是牺牲。

3. 但是，上海这种尝试所面临的压力也是非常巨大的，来自于周围省市的意见，来自于本地部分市民的不满。上海是全国医疗储备能力最强的两个城市之一，有很好的公卫防控机制，有强大的经济以保证民生，但是我们这几天仍然发现了一些问题，比如看病难问题，有护士哮喘发作，自己的医院都进不去，比如一些群众反映的买菜难问题等，再比如一些小微企业的生存困难问题等，这些都是必须想办法解决的。

4. 就像张文宏之前说过的，“上海这次战役，不搞一刀切，希望在尽量无疏漏筛查的同时能够最小化影响生活，肯定是非常不容易，也难免会不顺利，但也正显示了我们绝不肯走抗疫回头路的决心”。从来没有什么尝试是一帆风顺的，但是我们已经过了两年这样的生活，希望能够有所改变，尽可能减少疫情对正常生活的影响。

我也理解许多网友对上海的揶揄和嘲讽，包括一些红酒咖啡的段子。但上海这次大胆尝试，无论最终是成功还是失败，经验和教训都是属于全中国的。

任何一种防疫方式都是有代价的，区别只在于这个代价是什么。


* 周三 [[2022_03_30]] [[Mar 30th, 2022]]
** #今日鸡汤 #周记 #读书与思考

即使大部分人不会感恩，不要因此而停止做善事。这不仅因为做善事本身是一种高贵神圣的品质，而且在你实践过程中，你迟早会遇到某个人，非常感恩，他给你的（回报）远远弥补了其他所有人的忘恩负义。

** #今日文章 #周记

《上海疫情》

我的父亲沈瑞根，今年 77 岁，家住浦东新区北蔡镇（北中路 408 弄），由于糖尿病、肾衰竭正在血透治疗过程中，每日需高血压药、糖尿病的药、胰岛素、肾病药、脑中风药续命，因为浦东新区疫情封控管理处置不当，导致我父亲从一个尚能自主行为的老人，在 55 个小时内无辜惨死。

事情脉络如下：

3 月 26 日 应新区疾控中心要求，我父亲在复旦大学附属浦东医院做血透，因疫情封控我与弟弟无法出行陪同，唯 83 岁母亲伴随。

16:00 父亲做了两次核酸，显示阳性。

22:00 左右，父亲被要求送进急诊大厅的发热门诊隔离区，母亲核酸阴性需 120 急救车送回家，因 4、500 人排队，被告知需等待 7-8 个小时，只能独自一人坐在发热门诊大厅长凳，期间随身药物已用完，且已无法回家取药。

3 月 27 日 浦东医院告知不接受阳性病人做血透，父亲由新区疾控中心安排转运去君爱康复医院，但由于 120 急救已经超负荷调运，父亲一直未被安排。

3 月 28 日 8:50 老父亲终于由复旦大学附属浦东医院转送至上海君爱康复医院进行隔离。在君爱康复医院父亲在隔离病房无医生无护士进行照料与问询，除病友外父亲独自一人。

16:30 接到通知阳性病人可转至周浦医院做血透，但由于周浦医院人满为患，所以终止了他们这一批人过去（我父亲此时已四天未做过血透）。

21:30 父亲同病房病友电话我，告知父亲出现呕吐昏迷现象在 20:40 由 120 急救车送至周浦医院 ICU 病房。

21:52 左右，父亲亡故，无人告知家人。

3月29日 9:00 我拨通了周浦医院 ICU 电话，当班医生回答我说：你父亲沈瑞根于 3 月 28 日晚 21:52 在 ICU 病房因长期未肾透析造成的心肌衰竭而死亡。


* 周四 [[2022_03_31]] [[Mar 31st, 2022]]
** #今日鸡汤 #周记 #箴言

我不是要你的钱，我是用你的钱办你的事。

** #今日文章 #周记 #教育

《当代中国家长的现状》

1. 1-3 年级家长，最嚣张！因为啥题都会，一点都不慌。
2. 4-6 年级家长，变低调。因为偶尔不会，还不想让孩子知道。
3. 初中家长，低声下气。因为啥都不会，孩子还叛逆。
4. 高中家长变得勤快，题都看不懂，只好洗衣做菜。
5. 大学家长，最惆怅。没事不联系，联系就转账。


* 周五 [[2022_04_01]] [[Apr 1st, 2022]]
** #今日鸡汤 #周记

成年人几乎不会被别人改变，包括配偶，他们只是在自己的轨道上一直往前走或者原地踏步，我们只能去找志同道合的人。

** #今日文章 #周记

《不回德国的》

如果我能选择，我只想生活在自由、宽容、法律面前公民一律平等的国家里。公民自由意味着人们可以自由表达其政治信念；宽容意味着尊重别人的信念。目前德国还不具备这些条件。杰出人士包括第一流的艺术家正在那里受到迫害。

国家像人一样,面临严重的难题时也同样会害病。不过,国家患病通常
还能继续存在下去。我希望德国不久会得到恢复。我也希望像康德和歌德那样的伟大人物，不仅时常会被人纪念，而且永远活在人民的心里，永远受到世人尊敬。


* 周六 [[2022_04_02]] [[Apr 2nd, 2022]]
** #今日鸡汤 #周记 #上海疫情

江东只有 25% 的小区是防范区，浦东新区全部是管控区或封控区，至少封到 4 日结束，期间还要做一次核酸或者抗原自测，才可以判断是否继续封小区。

** #今日文章 #周记 #疫情

《吴尊有 无症状感染者比例非常高为何还要动态清零》

近一周，上海公布每日新增新冠病毒感染者人数，从2千多，增加到3千多、4千多、5千多。吉林公布每日新增感染者维持在2千多例左右。全国总体疫情也呈现每日新增感染者人数上升。大家一方面感到困惑，既然这波疫情的无症状感染者比例非常高，几乎都没有死亡病例，为何还要搞动态清零？另一方面，对近日的疫情上升，特别是上海、吉林这两起疫情的感染者总数都已经分别超过3万、4万例，还在持续报告大量新增感染者人数，非常担忧。

出现很大比例的无症状感染者主要有三个方面原因。第一，随着新冠疫苗接种率的提高，人群获得了对新冠病毒的免疫力，使得很大比例的感染者不出现症状；第二，奥密克戎变异毒株的致病性相对较弱，不及德尔塔和其他毒株的致病性强；第三，感染者发现比较早，一些确认病例在其尚未出现症状前就被筛查发现了。

大家看到我国现在报告的无症状和轻症比例非常高、重症及危重特别少且几乎没有死亡的现象，不是奥密克戎毒株在我国流行的自然结果，而是我国疫情防控措施落实显现的防控效果。同样是德尔塔毒株，在世界其他国家流行时造成了大量的病例死亡，当它传入我国出现输入性疫情流行时，也几乎没有造成死亡。同样是奥密克戎毒株，在欧美等国家流行时造成的死亡数，比同期德尔塔毒株流行造成的死亡还要高。奥密克戎毒株袭击香港时，短短3个月时间，在760万人口城市，造成超过113万人感染、近8千人死亡。所以，我们现在看到我国当前新冠疫情的重症和危重病例少、几乎没有死亡，主要是防控措施见效的结果。

我国之所以能够把重症/危重和死亡控制在非常低的水平，主要是疫情发现早、措施采取及时，特别是对所有感染者，包括无症状感染者都进行全程管理，对无症状和轻症及普通型病例给予中药等治疗，提高了病人免疫力，防止了病人从轻症向重症转化，规避了危重病例的发生，大幅度减少或基本预防了死亡。

上海、吉林等地在疫情发生一个月后，日新增感染者人数依然高达数千例，人们很担忧。应该看到，奥密克戎毒株具有潜伏期短、隐匿性强、传播速度快，及时控制疫情很困难。

虽然我们的防控措施把来势汹汹的奥密克戎毒株引发的新冠疫情感染者人数控制在一个相对较低的水平、死亡数控制在低水平，但现在还不是庆祝胜利的时候。当前的新冠疫情形势依然十分严峻，大家需要齐心协力，坚持坚持再坚持，努力尽快把这波疫情控制下去。

当一个省或市的新冠感染者总数在短时间内达到万人以上后，防控的难度就会明显加大。一方面是大量的感染者需要医疗服务，而医疗资源捉襟见肘；另一方面，因大量感染者产生的更大量的密接、次密接人员，需要可观数量的隔离观察设施，临时准备这些实施也面临极大困难；第三，当地的医疗防疫人员等数量明显不足，难以应对突如其来的对人员需求量的急剧增加。中国有“一方有难八方支援”的好传统，相信上海、吉林等疫情严重地区能度过难关，尽快战胜这波疫情。

应该看到，这波疫情是全球第四波疫情的尾声，只要我们坚持“动态清零”总方针，扎实落实各项措施，全国疫情形势一定会得到明显控制，回到全球第四波疫情流行前的水平。


* 周日 [[2022_04_03]] [[Apr 3rd, 2022]]
** #今日鸡汤 #周记

7

** #今日文章 #周记

7

