#+类型: 2205
#+主页: [[归档202205]]

* 周一 [[2022_05_09]] [[May 9th, 2022]]
** #今日鸡汤 #周记

在出入公共场所需持有 48h 核酸证明的要求加持下，很多人现在看到核酸点就想进去续下命。感觉现在活着就像是在玩那种点卡游戏，只有做了核酸才能在人间 online 续时长。 #疫情

** #今日文章 #周记

当你压力大到快要崩溃时的时候，不要跟别人讲，也不觉得自己委屈，没有人会心疼你。要像余华说的那样：在夜深人静的时候，把心掏出来，自己缝缝补补，然后睡一觉醒来，又是信心百倍。

无人问津也好，技不如人也罢，你都要试着安静下来，去做自己该做的事，而不是让烦躁和焦虑毁掉你本就不多的热情和定力。

心可以碎，手不能停，该干什么干什么在崩溃中继续前行，这是一个成年人的素养。


* 周二 [[2022_05_10]] [[May 10th, 2022]]
** #今日鸡汤 #周记

一个基本规律是，一个社会的常识越多，妄言就会越少。（访问速度咋样？

** #今日文章 #周记

良心

大学心理课上，一老教授问：“哪位同学能解释下什么是良心？”

一同学答：“良心是我心里一个三角形的东西。我没有做坏事，它便静静不动;如果我干了坏事，它便转动起来，每个角都把我刺痛；如果我一直干坏事，每一个角都磨平了，也就不觉得痛了。”


* 周三 [[2022_05_11]] [[May 11th, 2022]]
** #今日鸡汤 #周记

有些人本事不大，脾气却不小；反而那些本事大的人，温和了很多。

** #今日文章 #周记

学会如何去爱

我们只有完整地活过、爱过、期待过、争吵过、困惑过、痛苦过，才会明白自己到底想要怎样的生活，才能最终与自己的人生达成和解。

在此之前，我们唯一能做的，就是：学习如何去爱。

在爱的过程中，不断拓展自我界限，从中塑造出一个不同的、崭新的自己，实现自我完善；与此同时，不断奉献情感与智慧，聆听对方的声音，关注对方的需求，带动对方一起成长。

最后，我用诗人纪伯伦的《论婚姻》，来结束今天的文章：

你们的结合要保留空隙，让来自天堂的风在你们的空隙之间舞动。倒满各自的酒杯，但不可共饮同一杯酒，分享各自的面包，但不可吃同一片面包。

一起欢乐地歌唱、舞蹈，但容许对方有独处自由。就像那琴弦，虽然一起颤动，却发出不同的音，你是你，我是我，彼此各不相扰。

站在一起，但不可太过接近，把心扉向对方敞开，但不交由对方保管。

就像教堂的梁柱，各自耸立，支撑教掌不倒；就像橡树与松柏，也不在彼此的阴影中成长。


* 周四 [[2022_05_12]] [[May 12th, 2022]]
** #今日鸡汤 #周记

4

** #今日文章 #周记

4


* 周五 [[2022_05_13]] [[May 13th, 2022]]
** #今日鸡汤 #周记

5

** #今日文章 #周记

5


* 周六 [[2022_05_14]] [[May 14th, 2022]]
** #今日鸡汤 #周记

6

** #今日文章 #周记

6


* 周日 [[2022_05_15]] [[May 15th, 2022]]
** #今日鸡汤 #周记

7

** #今日文章 #周记

7

