#+类型: 2204
#+主页: [[归档202204]]

* 周一 [[2022_04_11]] [[Apr 11th, 2022]]
** #今日鸡汤 #周记

飞行员要求：思想进步、品德优良、遵纪守法、历史清白、现实表现好；拥护党的路线、方针、政策，思想进步，历史清楚，无重大违法违纪问题。

** #今日文章 #周记

《人世间》

“从你出生的那一刻，端什么碗，吃什么饭，经历什么事，什么时候和谁结婚，都是定数，别太难为自己，顺其自然就好。人生的剧本你早在天堂看了，你之所以选择这个剧本，是因为这一生中有你认为值得的地方。”


* 周二 [[2022_04_12]] [[Apr 12th, 2022]]
** #今日鸡汤 #周记

人啊，在哪儿都是混，但千万不要落到那些不如你的人手中。

** #今日文章 #周记

《新华社：一党独裁，遍地是灾》

打开我国的地图，睁开眼睛一看，国民党一党专政下的地区，哪里没有灾荒？单就报纸上发表的材料来看，可以看出灾荒是异常严重的。如湖南、河南、安徽、广东、广西、江苏、湖北、江西、四川，以及陕、甘、青、滇等省，真是遍地是灾，尤其是湖南等地，实在是惨不忍闻。

所以这些救灾的治本办法，只有走上和平、民主的道路时，才能完满解决。

--《新华日报》社论 1946 年 3 月 30 日


* 周三 [[2022_04_13]] [[Apr 13th, 2022]]
** #今日鸡汤 #周记

成熟的表现，有时是对“不成熟”的缺乏耐心。

** #今日文章 #周记

《活在当下》

很多人都以为自己 10 岁的时候不努力，20 岁的时候努力也不晚；很多人都以为自己 20 岁的时候不努力，30 岁的时候努力也不晚；甚至还有人觉得 30 岁的时候不努力，40 岁的时候日子还能越过越好。

他们基本上都是在幻觉中度过自己的一生的。

事实上，人越年轻，努力的效果越加倍，年龄越大，每一步努力极其艰辛。


* 周四 [[2022_04_14]] [[Apr 14th, 2022]]
** #今日鸡汤 #周记

或许不该主动去帮助别人。

** #今日文章 #周记

《男生真的会爱一个女生很久很久吗？》

不会，我老婆 18 年发现宫颈癌晚期，不到三个月就走了，在最后的日子里，我每天都在渴求奇迹的发生，也带着她到北京各大医院治疗，可是她还是离开了我和女儿，离开后的日子一段时间里，我真的无法接受，我不敢回家，家里的每个角落里都有她生活过的痕迹，我以为我这辈子都走不出去了。

可笑的是，19 年春天，老婆离开的第一个春节过后，我又结婚了，家里人介绍的，比我小 10 岁，30 岁出头的年纪，嫁给了我这个没了妻子的人，她年轻漂亮，和我女儿相处的也挺好生活继续着，家里关于我老婆的痕迹慢慢的消失了，我也沉浸在这个圆满的新家庭中。

直到上周，一家人在看月亮，女儿不经意间的说，今天月亮真圆，不知道妈妈在那边看见了没有，我这才意识到，我已经好久没有想起我的老婆了。


* 周五 [[2022_04_15]] [[Apr 8th, 2022]]
** #今日鸡汤 #周记

鼠疫流行的那些可怕的日子，在经历者的记忆中，不像火灾那样壮观而又残酷，倒像是无休无止的来回践踏，所经之处一切都碾压得粉碎。

** #今日文章 #周记

《你捅他呀》

医生正在抢救一位将军，旁边的护士突然掏出一把刀捅向了医生，在场的每一个人都震惊了。

护士带着泪水说：“对不起，我是卧底我知道你对我好，但是我不能让你救活他不能让他再说一句话。”

医生捂着伤口颤抖的说：“那你捅他啊！"


* 周六 [[2022_04_16]] [[Apr 15th, 2022]]
** #今日鸡汤 #周记

抱怨野蛮只需要一点勇气，理解文明却需要很多智慧。
嘲笑当权者是需要动用本能，同情弱者却需要很多的善良。
坚定对智慧和善良的追求，一开始很难，然后会慢慢进入正向循环。

** #今日文章 #周记

《无题》

现在还有很多人搞不懂，什么是资本主义？什么是社会主义?

简言之，就是说:
你的东西是你自己的，叫资本主义;
你的东西是政府的，就叫社会主义。

目前全世界 230 多个国家和地区只有 5 个是社会主义国家。


* 周日 [[2022_04_17]] [[Apr 16th, 2022]]
** #今日鸡汤 #周记

天地不仁，以万物为刍狗。

天地没有“仁”与“不仁”之说，没有偏私，对待万物都和对待刍狗一样 ，一切任其自然，这就是老子所讲的“道”。这句话其实是引子，想表达的是下面一句，就是“圣人不仁，以百姓为刍狗”，世间的圣人，应该效法天地，对待百姓就像对待同胞手足一样，无所偏爱，任其自然，这才是圣人之道。

** #今日文章 #周记 #程序员

《程序》

1. 代码写得好，bug 少，看起来就像一个闲人。
2. 注释多，代码清晰，任何人接手非常方便，看起来谁都可以替代
3. 代码写的烂，每天风风火火改。 bug，各种救火，解决各种线上重大问题，于是顺理成章成为公司亮眼的人才。
4. 代码乱的只有自己看得懂，才是公司不可替代的人才。
5. 多写 bug，一个好的程序员带动两个以上的兄弟就业，这样整个代码业就会繁荣发展，程序员们也不用像现在这么累。

