#+类型: 2205
#+主页: [[归档202205]]

* 周二 [[2022_05_24]] [[May 24th, 2022]]
** #今日鸡汤 #周记 #金融

经济学家不用信用卡我是相信的，因为有些人确实不需要。

信用卡本身能提供一个短期消费贷，只不过在免息期内你不用承担利息，对于一些人来说真的没必要需要这种消费贷。

对于教授这样的人管理自己小额信用贷实在太麻烦了，信用卡更适合中等收入人群使用，做一些资金流转和腾挪。

对于搞信用卡套现和卡债生活的人还是建议不要这么干，对未来自己信用等级有很大影响，除非你不需要房贷了。

** #今日文章 #周记

邓小平：直接提出六字方针“断交、废约、撤军”，断交是指美国必须立刻断绝与台湾的外交关系，台湾就是中国的一个地区，没有资格与他国建立外交关系，任何想要和台湾建立外交关系的国家，都是中国人民的敌人；废约是指废除美台之前所谓保护彼此安全而签订的共同防御条约，美国不得为台湾提供武器和保护。撤军是美国军队立刻滚出台湾，并保证以后不得在台湾建立军事设施。看到中国的强势态度，万斯不敢继续在中国的地界上嚣张了。


* 周六 [[2022_05_28]] [[May 28th, 2022]]
** #今日鸡汤 #周记

最上等的合作，是志同道合。次一等的，是狼狈为奸。最糟糕的，叫与虎谋皮。 ​​​

** #今日文章 #周记

如果自费药、自费耗材全进医保，让医院里每个病人都能敞开了用自费药，那么全国每年死亡人数必然大幅降低，人均寿命必然得到大幅提高。到年底一算，会发现今年少死了很多人，而以前每年都比今年多死了很多人。

但还有很多自费药没办法进医保。因为医保没那么多钱。那么，如果把现在医保缴费翻十倍是不是就好很多？医保缴费翻十倍，不过是每个人收入低一点、生活差一点，然而却可以救很多人的命。那为什么不这样做呢？

中国血库一直是比较短缺。所以临床输血比较难。白蛋白、球蛋白、凝血因子等等这些血制品也因此比较缺。如果这些短缺问题解决了，那么全国每年死亡人数必然大幅降低，人均寿命必然得到大幅提高。到年底一算，会发现今年少死了很多人，而以前每年都比今年多死了很多人。

如果要求每个青壮年每年必须献血两次，不献血就进征信，不能坐高铁乘飞机，那么血库短缺问题必然迎针而解。如果说医保多缴费会让收入低一点、生活差一点，会影响经济什么的，而强制献血并不会。只是每年扎两针，稍微有点疼，年轻人怕什么疼呢？然而却可以救很多人的命。那为什么不这样做呢？

因为社会运转既需要提倡集体主义也需要保护个人自由。集体主义对个人自由的侵犯必须要有一个界限。否则，最终会死更多人。这个实验我们以前做过。


* 周日 [[2022_05_29]] [[May 29th, 2022]]
** #今日鸡汤 #周记

7

** #今日文章 #周记

7

