#+类型: 2204
#+主页: [[归档202204]]

* 周一 [[2022_04_04]] [[Apr 4th, 2022]]
** #今日鸡汤 #周记 #程序员 #人生


如果你不知道如何开始你的设计（不管是什么设计），我倒是有一个通用的方法，简单描述如下： 

目的 -> 流程 -> 成分 -> 关系 -> 平衡。

** #今日文章 #周记

《结婚的意义》

结婚的意义是什么？

这是我听到非常喜欢的答案 —— 结婚是为了：

一个相爱相知相伴的人在生活中能给你勇气；

遇到事能有个人商量；

在生活累的时候彼此相互安慰鼓励；

在外受了委屈回到家有个温暖的拥抱。

我开着车，你坐在副驾驶车里放着我们相互听的音乐一起下班回家浪漫、吃饭。

愿你此生 终得一人	
暖你心窝 伴你终老


* 周二 [[2022_04_05]] [[Apr 5th, 2022]]
** #今日鸡汤 #周记 #上海疫情

大会上的讲话(要点：)
上海的错误不在于探索新的防疫方法，这种探索是值得肯定和鼓励的。

上海的错误在于没有底线思维，没有划清底线，没有为底线突破以后做足够的准备，结果就是破防了不愿承认，爆发了没有准备，各种资源被刺穿，应检尽检应收尽收做不到了还在硬杠，总之一句话，丢掉了党的实事求是的原则。


** #今日文章 #周记 #疫情

《辉瑞》

辉瑞的新冠特效药，确实有点贵，但并非贵的离谱。

注意：这种药只需服用 5 天，一疗程正好 1 盒的量。

不是是这药一盒 2300，得吃好几盒。而是一盒 2300，吃一盒就够了。

一个患者 2300 元，还是贵，能降到 200 左右最合适。

这种可能性很大，新冠国产灭活疫苗早期采购价是 200，现在不到 20。量上去了，价就能下来。

至于说这药应该自费的，我就纳闷了：这款药物能降低 88% 的重症风险，改成自费的话，谁舍不得这 2300？是有钱人还是穷人？

大概只有最贫困的那部分中国老百姓，才会舍不得吃这药。

让这药自费，是觉得穷人该死吗？


* 周三 [[2022_04_06]] [[Apr 6th, 2022]]
** #今日鸡汤 #周记

3

** #今日文章 #周记

3


* 周四 [[2022_04_07]] [[Apr 7th, 2022]]
** #今日鸡汤 #周记

4

** #今日文章 #周记

4


* 周五 [[2022_04_08]] [[Apr 8th, 2022]]
** #今日鸡汤 #周记

5

** #今日文章 #周记

5


* 周六 [[2022_04_09]] [[Apr 9th, 2022]]
** #今日鸡汤 #周记

6

** #今日文章 #周记

6


* 周日 [[2022_04_10]] [[Apr 10th, 2022]]
** #今日鸡汤 #周记

7

** #今日文章 #周记

7

