#+类型: 2203
#+主页: [[归档202203]]

* 周一 [[2022_03_28]] [[Mar 28th, 2022]]
** #今日鸡汤 #周记

疫情是个照妖镜，上海终归是中国的，和其他任何的国内城市并无本质区别。

** #今日文章 #周记

《上海抗疫》  #上海疫情

上联：浦东决战愚人节
下联：浦西决战清明节
横批：欢欢喜喜劳动节


* 周二 [[2022_03_29]] [[Mar 29th, 2022]]
** #今日鸡汤 #周记

人以是非定立场，
奴以立场定是非，
兽以食物定立场，
魔以成败定是非。


** #今日文章 #周记

《上海疫情》 #上海疫情

1. 在某种程度上，上海这次的防控方式是一种非常有必要的尝试，而这种尝试也只能在上海这个过去两年的防疫优等生上进行（我想有不少人对这一点持不同看法，以你的看法为准）。

2. 为什么要进行尝试，因为 BA.2 传染性和致病力的变化，因为疫苗接种率的变化，因为过去的一些防疫方式造成的次生问题大家有目共睹。

尽管国内很多人对防疫方式存在争论，但是比较明确的一点是处于极端的人并不多，基本没有人会同意直接像一些国家那样全面放开，也基本没有人会同意严防死守到病毒灭绝，但是大家都不清楚的一点是，目前这样的防控方式究竟能持续多久，未来是否会有阶段性变化。

如果没人尝试，我们只能原地踏步。实际上在过去面临各种传染病时，人类总是在不断地试错，有句话叫做“站在巨人的肩膀上”，你今天看到各种各样成功的防疫方式，背后都是大量的尝试，甚至是牺牲。

3. 但是，上海这种尝试所面临的压力也是非常巨大的，来自于周围省市的意见，来自于本地部分市民的不满。上海是全国医疗储备能力最强的两个城市之一，有很好的公卫防控机制，有强大的经济以保证民生，但是我们这几天仍然发现了一些问题，比如看病难问题，有护士哮喘发作，自己的医院都进不去，比如一些群众反映的买菜难问题等，再比如一些小微企业的生存困难问题等，这些都是必须想办法解决的。

4. 就像张文宏之前说过的，“上海这次战役，不搞一刀切，希望在尽量无疏漏筛查的同时能够最小化影响生活，肯定是非常不容易，也难免会不顺利，但也正显示了我们绝不肯走抗疫回头路的决心”。从来没有什么尝试是一帆风顺的，但是我们已经过了两年这样的生活，希望能够有所改变，尽可能减少疫情对正常生活的影响。

我也理解许多网友对上海的揶揄和嘲讽，包括一些红酒咖啡的段子。但上海这次大胆尝试，无论最终是成功还是失败，经验和教训都是属于全中国的。

任何一种防疫方式都是有代价的，区别只在于这个代价是什么。


* 周三 [[2022_03_30]] [[Mar 30th, 2022]]
** #今日鸡汤 #周记

3

** #今日文章 #周记

3


* 周四 [[2022_03_31]] [[Mar 31st, 2022]]
** #今日鸡汤 #周记

4

** #今日文章 #周记

4


* 周五 [[2022_04_01]] [[Apr 1st, 2022]]
** #今日鸡汤 #周记

5

** #今日文章 #周记

5


* 周六 [[2022_04_02]] [[Apr 2nd, 2022]]
** #今日鸡汤 #周记

6

** #今日文章 #周记

6


* 周日 [[2022_04_03]] [[Apr 3rd, 2022]]
** #今日鸡汤 #周记

7

** #今日文章 #周记

7

