#+类型: 2203
#+主页: [[归档202203]]

* 周一 [[2022_02_28]] [[Feb 28th, 2022]]
** #今日鸡汤 #周记

有些牙刷，刷了一辈子牙坏掉的時候还得去刷皮鞋、刷浴缸。

** #今日文章 #周记

《世上最廉价的东西》

一个很现实的故事；
一个女孩跟富二代跑了，几年之后遇到前男友，前男友问她：“富二代真的比我好吗？你胃不好半夜经常疼。我每天早上去市场，买最新鲜的姜切成片放在你身边，让你不舒服的时候含着。我现在刀功都快赶上厨师了，他能为你这么做吗？”女孩淡淡地回答：“没有，他花 30W。带我去大医院治好了胃病。”

呵呵……，世上最廉价的大概就是付出吧。一贫如洗的真心，一事无成的温柔。


* 周二 [[2022_03_01]] [[Mar 1st, 2022]]
** #今日鸡汤 #周记

学到一个新词—轻松成功学，大概是说通过不太努力、或者有捷径的轻松努力就能成功的一个概念。发现这个概念太真实了，确实有不少这样的人，也有不少这样的事。比如七天入门系列、某某叫你稳赚不赔、你离成功只差xx等等。每个人都梦想轻松成功，是人性，轻松成功学轻松成功了。

** #今日文章 #周记

《我缺一个女朋友》

如何用鲁迅的笔风，说自己缺一个女朋友

我大抵是病了
横竖都睡不着
坐起来点了一支烟
这悲伤没有由来
黯然看着床头的两个枕头
一个是我的
另一个大抵也是我的.....


* 周三 [[2022_03_02]] [[Mar 2nd, 2022]]
** #今日鸡汤 #周记

智者不入爱河，寡王一路硕博，信女吃斋念佛，荣华富贵生活。

** #今日文章 #周记

《变了》

以前，
父亲掏出口袋里的钞票，
我们一眼能看出他的窘迫！

如今，
我们拿出手机扫码付款的时候，
孩子却以为里面有用不完的钱…


* 周四 [[2022_03_03]] [[Mar 3rd, 2022]]
** #今日鸡汤 #周记

“我18岁开始从古典文学中汲取许多知识，其中之一当时并不完全理解，那就是希腊作家普鲁塔克所说：我们内心获得的，将改变外在的现实”。 —— J. K. 罗琳哈佛大学演讲

** #今日文章 #周记

《王蒙讲孔孟老庄》

“六十而耳顺”，到了六十岁，听得进去话了，能接受别人对自己的忠 告、教诲了，能够自我反思，能够有一种自我调整的能力了，也有不较劲的意思，也有一点自己清醒了的意思。

解惑是在四十岁，知天命是五十岁，是十年之后，二十年以后才能做到耳顺，说明耳顺是不容易的，听得进去话、接受得了忠告是不容易的，这是很有意味的。

学会说话不容易，学会听话在某种意义上更不容易，所以孔子这位老先生对事物的分析都不是偶然的。


* 周五 [[2022_03_04]] [[Mar 4th, 2022]]
** #今日鸡汤 #周记

从这次冲突得知：
朋友的敌人是敌人，敌人的敌人是朋友。
中立的也是敌人，弃权的还是敌人。
反正不支持我的，都特么是敌人！

** #今日文章 #周记

《人到中年》

清明到来，我就 38 岁了，日暮乡关之感如针锥心薄雾从村头飘来，坐在橘园里，一些病果尚在枝头蒲公英又一次开出黄色的花，如一年一发的寂寞。

能够思念的人越来越少。我渐渐原谅了人世的凉薄如果回到过去，我确定会把爱过的人再爱一遍把疼痛过的再疼一遍。

但是我多么希望没有病痛的日子，一年或者一星期在春天的风里跳舞，踮起脚旋转他能看见也好，不能看见也罢。

我只有一个愿望：生命静好，余生平安在春天的列车上有人为我让座不是因为我摇晃的身体。


* 周六 [[2022_03_05]] [[Mar 5th, 2022]]
** #今日鸡汤 #周记

真正可怕的坏人是那些不知道自己坏，反而认为自己正确，认为自己很好的人，他们没有良心，却挥舞着良心的大棒打人，他们没有道德，却始终占据着道德高地。—— 莫言 #名人名言

** #今日文章 #周记

《战士和苍蝇》

Schopenhauer 说过这样的话：要估定人的伟大，则精神上的大和体格上的大，那法则完全相反。后者距离愈远即愈小，前者却见得愈大。

正因为近则愈小，而且愈看见缺点和创伤，所以他就和我们一样，不是神道，不是妖怪，不是异兽。他仍然是人，不过如此。但也惟其如此，所以他是伟大的人。

战士战死了的时候，苍蝇们所首先发见的是他的缺点和伤痕，嘬着，营营地叫着，以为得意，以为比死了的战士更英雄。但是战士已经战死了，不再来挥去他们。于是平苍蝇们即更其营营地叫，自以为倒是不朽的声音，因为它们的完全，远在战士之上。

的确的，谁也没有发见过苍蝇们的缺点和创伤。

然而，有缺点的战士终竟是战士，完美的苍蝇也终竟不过是苍蝇。

去罢，苍蝇们！虽然生着翅子，还能营营，总不会超过战士的。你们这些虫牙们！


* 周日 [[2022_03_06]] [[Mar 6th, 2022]]
** #今日鸡汤 #周记 #战争

俄乌战争是对全球化的重重一击。经济金融制裁及各大公司的主动在商业上参战，让几大主要经济体都认识到在关键物资、产业、基础设施和技术上独立自主自给自足的重要性。全球化有赖于大家对全球范围内进行资源配置和生产要素全球自由流动方为最佳方式这一理念的信仰。

** #今日文章 #周记

《赌咒》

“天诛地灭，男盗女娼” 一是中国人赌咒的经典，几乎像诗云子曰一样。现在的宣誓，“誓杀敌，誓死抵抗，誓……”似乎不用这种成语了。

但是，赌咒的实质还是一样，总之是信不得。他明知道天不见得来诛他，地也不见得来灭他，现在连人参都“科学化地”含起电气来了，难道“天地”还不科学化么!至于男盗和女娼，那是非但无害，而且有益：男盗 —— 可以多刮几层地皮，女娼 —— 可以多弄几个“裙带官儿”的位置。

我的老朋友说：你这个“盗”和“娼”的解释都不是古义。我回答说 —— 你知道现在是什么时代！现在是盗也摩登，娼也摩登，所以赌咒也摩登，变成宣誓了。

