#+类型: 2204
#+主页: [[归档202204]]

* 周一 [[2022_04_18]] [[Apr 18th, 2022]]
** #今日鸡汤 #周记

不把你饿到半死不活，你又怎么可能会感恩戴德呢？

** #今日文章 #周记

《不要掉入“人生的意义就是吃”的执念里》

人生虽是一连串“为了什么”的集合，但若认为真正的目的只是如此，就会感到空虚。例如塞在通勤的车阵里，心里想的是：“真是浪费时间！只是为了去上班而已。”这样的想法只会让人疲惫。但是，若把通勤时间拿来学英文，就能把原本“为了移动”的虚无目的，转换成“增加知识”这个有意义的目的了。如此，就会感到幸福，这就是亚里士多德的解决方法。


* 周二 [[2022_04_19]] [[Apr 19th, 2022]]
** #今日鸡汤 #周记

西方观点：没有自由，生命有什么用；中方观点：没有生命，自由有什么用。这次上海的封城让这个辩论赛结束了：没有自由，你会被饿死！

** #今日文章 #周记

《非必要离校》

实习 挂号 雅思 课算是必要的吧
那 蹲守一朵飞檐上的云呢
捂回一袋板栗呢
被落叶淋上头发呢
坐两个小时昏昏欲睡的校车
去牵另一半的手呢
万一 这张照片被传成经典呢
万一 这袋板栗分给了一个濒临崩溃的同学呢
万一 淋湿的是一个诗人呢
万一 这辈子就是他呢
疫情 让一切都变成了正襟危坐的必要
诶 人间是由无数个非必要组成的呀

朱皓月 中央美术学院


* 周三 [[2022_04_20]] [[Apr 20th, 2022]]
** #今日鸡汤 #周记

《唱支山歌给党听》作曲者朱践耳的夫人在上海去世，因为封锁耽误 6 个小时没及时抢救。医院太平间冰柜放满遗体，她的遗体只能扔地上。两子女都在美国！前几天是《我爱？你，中国》原唱叶佩英去世！

** #今日文章 #周记

《无题》

上海这轮疫情持续了一个多月了，发生了很多怪事，一样接着一样：
1. 要求市民足不出户，但是吃饭问题要自己解决；
2. 菜价涨了 2-3 倍不等，跑腿费涨价 5-10 倍不等，给少了还不送；
3. APP 上抢不到菜，但是团购物资充足，发货也快，很多第二天就能到；
4. 京东不是保供单位，进城物资被堵三天。高价团购物资天天可以进来；
5. 外地的援助物资居然可以买到；
6. 每天确诊+无症状人数精准控制在23000-25000人；
7. 普遍发莲花清瘟，有的小区还不止发了一次，又告知没感冒不要吃，是钱太多了没处花？而有的方舱居然没有发到药！难道不是应该把药发给阳性人员吗？
8. 天天又是核酸检测又是抗原检测，反复做，扎堆做核酸还有交叉感染风险，意义在哪里？
9. 阳性的人健康云不显示，只是以疾控中心电话告知，人不及时拉走，有的人还能持有阴性报告出城；
10. 封闭了一个多月的小区，还能冒出阳性；
11. 各种辟谣，又以造词的形式验证；
12. 电视上上海物资充足，市民情绪稳定，甚至还要举办晚会。


* 周四 [[2022_04_21]] [[Apr 21st, 2022]]
** #今日鸡汤 #周记

“我相信我们的党总有一天会作出这样的历史决议：永远永远地严禁个人崇拜。因为一搞个人崇拜，就根本谈不上什么民主，谈不上实事求是，谈不上解放思想，就必然要搞封建复辟。其危害之烈莫此为甚。” —— 胡耀邦 于 1976 年

** #今日文章 #周记

《美国对外军事行动的国际法依据》

1. 1950 年朝鲜战争：联合国安理会第82、83、84号决议，谴责朝鲜侵略韩国，授权美国组成联合国军，使用联合国旗帜，军事行动直接向联合国安理会报告。

2. 1990 年海湾战争：联合国安理会第 660、661、662、664、665、666、667、678、669、670、674、677 号决议，谴责伊拉克占领科威特，授权美国以一切手段把伊拉克军队赶出科威特。中俄投赞成票。

3. 1999 年科索沃战争：联合国安理会第 1160 号决议，要求南斯拉夫政府停止暴力行为，允许北约监督停战。俄罗斯投赞成票，中国弃权。

4. 2001 年阿富汗战争：联合国安理会第 1267、1333 号决议::将塔利班和本·拉登界定为恐怖组织和恐怖分子，授权美国以一切手段打击恐怖组织。中俄投赞成票。

5. 2003 年伊拉克战争：联合国安理会第 1284、1441 号决议：要求伊拉克遵守停战协议、裁军、停止生化武器研究。中俄投赞成票。
6. 2011 年轰炸利比亚:联合国安理会第	1970 号决议：指控卡扎菲犯反人类罪。中俄投赞成票。

7. 2015 年介入叙利亚内战：联合国安理会	第 2042、2043、2118、2170、2199 号决议：确认 ISIS 为巩怖组织，要求叙利亚政府销毁化学武器。中俄投赞成票。


* 周五 [[2022_04_22]] [[Apr 22nd, 2022]]
** #今日鸡汤 #周记 #人生 #教育

别人的 BUG，就是我们成就的机会。人人都三分钟热度，四处撒网，眼高手低，我们就专做一件别人觉得有点费力的事情，别人觉得不起眼的事情，就把这件事情做透做深，让别人仿不了，学不会。等他们绕了一圈回来，还得像你学习，虽然你开始得比别人还要晚。

** #今日文章 #周记

《执行力强》

关羽冲进帐来：“被包围了，大哥快走！”刘备：“云长，帮我断后！"关羽手起刀落把刘禅砍成两截。

刘备：“尼玛，我说的不是这个！"关羽又砍死刘封。

刘备：“靠！也不是！”关羽刀光一闪，刘备两腿间一片血红……

启示：没有理解组织的战略，执行力强只是个悲剧。


* 周六 [[2022_04_23]] [[Apr 23rd, 2022]]
** #今日鸡汤 #周记 #历史

清乾隆帝致英国国王乔治三世的信函：“天朝物产丰盈，无所不有，原不藉外夷货物以通有无。”

** #今日文章 #周记

《官场现形记！》

上海辟谣。

辽宁辟谣上海的辟谣。

上海再次辟谣辽宁辟谣的有关上海的辟谣的辟谣。

辽宁忍无可忍拿出了终极证据辟谣了上海再次辟谣的有关辽宁辟谣的有关上海辟谣的辟谣的辟谣的辟谣。


* 周日 [[2022_04_24]] [[Apr 24th, 2022]]
** #今日鸡汤 #周记

7

** #今日文章 #周记

7

