#+类型: 2203
#+主页: [[归档202203]]

* 周一 [[2022_03_21]] [[Mar 21st, 2022]]
** #今日鸡汤 #周记

如果有人跟你扯什么一个巴掌拍不响，别犹豫，上去就给他一巴掌，这时他肯定立马暴怒。你反问他：我这是怎么拍响的？他肯定继续暴怒：我他妈那是个比喻！我意思是说不要觉得谁都是在莫名其妙别人，被欺负那个人应该先反思自己！这时你可以说：对啊，所以你挨这一巴掌也应该先反思一下自己。

** #今日文章 #周记

《也许你的顿悟，只是别人的基本功》

我曾经在《定位》一书中看过这样一句话，非常的震撼。

原话是这么说的：

任何问题都不是孤立存在的，一定有人曾经遇到过，并且已经有更好的解决办法了，只是我还不知道；我不应该在黑暗中独自前行，也许我的顿悟，只是别人的基本功！我应该站在巨人的肩膀上，学习更成熟的经验和方法，然后再来解决这个问题。

中间有一句话特别扎心”也许你的顿悟，只是别人的基本功”。

所以我现在就特别警惕这件事，做任何事情的时候，我都要停下来，先去找一找这个领域有没有巨人，如果有，先用知识树学一遍，然后再去实操。这也是我之前反复在提的”二元学习法”，很多人都是经验主义者，他们不喜欢学习巨人的知识，只喜欢靠自己的感悟去获得成功。

自己的感悟当然也很重要，但是如果只有自己的感悟，就会出现三大非常大的问题：

第一，你会走很多弯路。因为你每个坑都要趟一遍，甚至趟几遍。
第二，成功的速度比较慢。经验主义者很多是大器晚成，而且他们的成功都是靠经验堆出来的，走了很多弯路。
第三，天花板比较明显。因为成功的边界，就是你认知的边界。

所以，一定要有巨人思维，向有结果的人学习。虽然别人的经验无法完全 100% 复制给你，但是如果你能用 10 个小时的时间，就学到别人辛辛苦苦几十年时间感悟的东西的 50%，那也非常划算了是不是？

大多数人都只是身体上很勤奋，但是思想上很懒惰，他们不懂得站在巨人的肩膀上前行，即使你跟他说，巨人思维很重要，他们依然会觉得”哦，是吗？但是我觉得只有我自己亲身经历的才是自己的。

这，有点傻。


* 周二 [[2022_03_22]] [[Mar 22nd, 2022]]
** #今日鸡汤 #周记

有一辆 70 年的山寨德国车都快散架了，既不肯换发动机，也不肯换刹车。

乘客们还天真的以为只要换个驾驶员就好了。厉害的是这辆破车涂上了一身红漆后竟然准备上高速公路。更要命的是，现在的驾驶员一边开车还一边做梦！最近又开上了逆行车道，还不许乘客打开窗户看外面……


** #今日文章 #周记

《对着干》


社会和教育系统的目的，跟个人的意愿是有冲突的。很多人说要相信学校，相信政策，相信社会，未来会越来越好。这点根本上讲没错，因为政策刺激经济，经济促进社会，社会发展做大蛋糕，最后每个人分到的自然就多了。

但社会和教育系统的目的是让你领蛋糕，而个人奋斗的目的是做那个切蛋糕和抢蛋糕的人。

社会和教育系统自然不可能鼓励所有人都这么做，更不可能传授切蛋糕抢蛋糕的方法。所以按部就班的跟着政策跟着社会跟着学校，最后的结果就是永远只能在时代温饱平均水平线上下挣扎。

对比以往，比如 20 年前，温饱水平线确实提高了，客观来说你确实变好了，进步了。但这只是纵向，横向来说你其实没什么变化。知识媒体说现在的白领和以前父母时代的工人农民没太大区别，指的就是这么回事。

因此很多人说学校和社会不接轨，不教点真正有用的，学校本来就不能教点有用的。教点有用的，每个人都精明能干，都情商爆表，都游刃有余，毕业了之后都独当一面，快速升职。问题就来了，社会哪有那么多管理类的高薪岗位？

全国的 211、985 每年毕业人数，起码大几十万快接近 100 万了，这些人各个都想要高薪想要管理，这咋样都办不到哇。只能用自然筛选机制，即不是教育，而是放马跑，自然筛选。

天赋好的极少数，筛选出来通过竞争，可以独当一面成为管理者。天赋普通的，天赋差的，不教育，不教导，自然发展，毕业了自然成为螺丝钉，底层小卒。整个机制就是这么安排的。

所以你特别在意老师家长的话，积极配合，基本上最后不会有什么好结果。因为你必须明白这个常识：哪怕是天赋好的人，他也不是靠学校教育取胜的，都是靠自学。那天赋普通和天赋较差的，就更要投入千百倍的努力去自学了。


* 周三 [[2022_03_23]] [[Mar 23rd, 2022]]
** #今日鸡汤 #周记

不要因别人不能成为我们所希望的人而愤怒，因为我们自己也难以成为自己所希望的人。

** #今日文章 #周记

《珍惜当下》

通过客机事件和今年的疫情，仿佛在提醒我们：

钱财再好，也好不过生命，名利再大，大不过健康。人间的饭，吃一碗少一碗，人间的面，见一面少一面。人生本就是一次次减法，来日并不方长。

这个世界我们只来一次，所以，吃你想吃的饭，见你想见的人看喜欢的风景,做你喜欢的事，你永远不知道明天和意外哪个先到。所以，珍惜现在的每一分每一秒。


* 周四 [[2022_03_24]] [[Mar 24th, 2022]]
** #今日鸡汤 #周记

林徽因说：人与人之间，若灵魂不能共振，交流不能同频，仅仅只是浅浅的遇见，终究会成为陌路，各自天涯。 #名人名言

** #今日文章 #周记

《如何找到自己一生的热爱、喜欢的工作？》

唯一的解决办法，就是多尝试，多经历。

真的没有别的办法。

有些人很幸运，他们很容易知道自己的兴趣点，干这个就很开心，干别的就很痛苦，特别明显。

但有些人则不知道自己真正感兴趣的是什么，可能花一辈子的时间都在寻找。

针对寻找自己热爱的东西，我可以分享的思路是：

1、有哪些事情，是你毫无费力，就能做的很好的。

2、你人生中坚持的最长时间的事情是什么？

3、有什么事情，不给钱也愿意做？

4、无所事事的时候，你愿意做哪些事？

5、去主动尝试一些你从没尝试过的事情。

6、多读书，有时候看书时会有灵感迸发。

7、多做事，比起躺着，多做事更容易碰到自己的兴趣点。如何找到自己一生的热爱？喜欢的工作？


* 周五 [[2022_03_25]] [[Mar 25th, 2022]]
** #今日鸡汤 #周记

没有受过资本主义一天苦，愣是批了它七十多年；没有享过共产主义一天福，愣是要为它奋斗终生。

** #今日文章 #周记

《写作的目的》

99.99% 的人都没搞清楚写作是什么。

写作不是阅读，不是笔记，不是思考，不是想法，不是散步，不是习惯，更不是什么工具，流程，方法，系统。

写作是明知没有才华时，
你还继续写。

写作是始终无人问津时，
你还继续写。

写作是遭受冷嘲热讽时，
你还继续写。


* 周六 [[2022_03_26]] [[Mar 26th, 2022]]
** #今日鸡汤 #周记

大多数人的一生都殚精竭虑、费尽心机地为得到幸福而努力。他们制订让自己幸福的计划，为了搜集幸福的点滴去旅行、去工作。当生命离去时，他们才意识到，幸福的碎片永远搜集不够，幸福只是过程。他们忘记了这个。 —— 马洛伊·山多尔《草叶集》

** #今日文章 #周记

《你告诉我什么是爱？》

一个真实的故事，一对夫妻结婚几年没有怀孕，婆婆天天给媳妇脸色看，老公夹在中间很是无助。

一天丈夫拿来一份检查报告显示他不能生育。媳妇爆发了这些年的隐忍委屈一下子出来了。婆婆看到这场面明白了马上讨好儿媳妇不能离婚，离了她的儿子肯定娶不到媳妇了。

丈夫对她说尊重你的选择。媳妇想了一晚上决定离婚。这么多年来，他们是有感情的，一直是婆婆作祟，现在婆婆改变了，早上做她喜欢的饭菜，连家务也不让她做，她想这辈子没有孩子就这么过吧，领养一个吧。

后来领养了一个男孩。

十几年后婆婆去世了，儿子也上大学了。她在家收拾屋子把每个角落都大扫除，这时候她看到一份检查报告，当年不能生育的是她，不是她丈夫。

她瞬间汨崩，是她的丈夫把过错都推在了他身上了。她问他丈夫为什么连她也隐瞒，丈夫说你这个人脸上藏不住事你会装的不像，我妈会怀疑的，我不这样做我怕我妈会逼我离婚，我不想离婚，哪怕你不能生育，我没有自己的亲生孩子也不想和你离。


* 周日 [[2022_03_27]] [[Mar 27th, 2022]]
** #今日鸡汤 #周记

台湾有一项政策，所有吃不饱的孩子，都可以到指定便利店领免费便当。一位台湾导游不明白的是，总有大陆游客听说后问她：怎样防止有孩子去冒领便当？

她觉得特别奇怪，如果可以吃饱了，谁愿意去领免费的便当呢？人是需要尊严的啊！

** #今日文章 #周记

《人人都有病》

孙中山：中国人人有病。
康有为：什么病？
孙中山：愚昧之病。
康有为：愚在何处啊？
孙中山：被奴役着却以为自由着，从来不知道平等为何物，不知自爱也不懂爱人。一句话，奴才不知道自己是奴才。
康有为：病根何在？
孙中山：这就多了，四书茶毒生灵，五经钝化人心，三纲生产奴才，五常捆绑性情。

总之，在信仰的荒芜上绝立不起一个伟大的民族。

