#+类型: 2203
#+主页: [[归档202203]]

* 周一 [[2022_03_07]] [[Mar 7th, 2022]]
** #今日鸡汤 #周记

人的一生，其实就是时间和注意力分配的过程，你所专注的一切，反过来定义了你是谁，因此要格外珍惜你的注意力，认真选择你的情绪和思想所聚焦的对象。
如果你只是不停被喧嚣带走注意力，或总是纠结于错误的事与人，迟早你会被外界塑造或污染，成为你不想成为的人，白白浪费掉你仅有一次的生命。

** #今日文章 #周记

《战争》

战争就是某个大人物打着国家的旗号，驱赶底层老百姓上战场血拼。一个农民的儿子奔赴万里去杀死素不相识的另一个农民的儿子。最后死去的农民儿子得到的只是被吹得无比神圣的一块铜制的小牌牌和一面旗帜。父母失去了儿子，妻子失去丈夫，儿女失去了父亲。而无数农民儿子用命换来的却是那个大人物坐稳的宝座和一生的富贵。


* 周二 [[2022_03_08]] [[Mar 8th, 2022]]
** #今日鸡汤 #周记

中国人的神逻辑一：1. 你饭都没吃饱还关心这个干嘛？2. 你都吃饱饭了还关心这个干嘛？
中国人的神逻辑二：1. 上面的政策是好的，都是下面的人把经念歪了；2. 下面的人也没办法，都是上边要求的。


** #今日文章 #周记

《二零二二年三月六日》

在这儿你不能愤怒，否则你会时时处于愤怒中，而愤怒无济于事，除了微弱地证明你的心还没有变成铁、变成水泥、变成塑料，或者随便什么。

那么你该怎么办没错，她不是你，早晨醒来你的脖子上没有一根锁住的铁链，昨晚你也不在逃难的人群中，你的天空没有炸弹在飞，你窗前的花像从前一样迎接春日。

但此刻你感到快乐是一种羞耻，平静地生活是一种羞耻。

20220306


* 周三 [[2022_03_09]] [[Mar 9th, 2022]]
** #今日鸡汤 #周记

兜兜转转，很多人还是找不到自己真正需要什么东西的，这恐怕就是人生。 #箴言

** #今日文章 #周记

古典《跃迁：成为高手的技术》）


查理·芒格说：“要获得什么，先让自己配得上。”这也是在重新定义问题——得不得是外控的、无解的，但是配不配是内控的、有解的。

举个有趣的例子，谈谈皇帝们如何管控一个思想的多层体系。

封建国家没有互联网，大伙儿怎么想，主要看几个文化人怎么说，所以封建国家很重视思想控制，摧毁或者至少控制自由知识分子的思想。好，现在给你个机会穿越。如果穿越到古代，成为皇帝，要控制知识分子，你该怎么办？

方案 A：焚书坑儒——物理层面摧毁信息源，生理层面摧毁人，简单粗暴快，但春风吹又生。而且国家也暴戾十足，很快灭亡，如强秦。秦始皇不懂系统思考啊。

方案 B：文字狱——生理层面摧毁一小部分，心理层面的震慑大多很有效。但是文人马上变着法儿迭代，写个小说映射你，写个藏头诗挤对你，防不胜防，如清朝各种小说。

方案 C：找群宫廷文人，与之写文对骂——这个效果不佳，历来文章写得好的都是自由的灵魂，拿俸禄的效率不高。
这些以暴易暴的线性思维对文化人不好用啊，最后设计出来最精妙的，是一套自上而下的系统解决方案。

方案 D：科举制度——设计一套在自我实现（家国天下）、归属感、认同感（光宗耀祖、封妻荫子）、生理和心理（颜如玉、黄金屋）方面符合马斯洛需求层次理论的完整多层结构，以及自上而下降维攻击的解决方案，直接改变价值观。开科取士，天下共趋之。

什么？写自由议论文？别闹，老子正准备考试呢！

这个封闭的小系统非常有效，从内部几乎完全不可灭。一直到1840年我们集体被炮声震醒，被更高层级降维攻击，即现代社会的科学、民主与经济体系，我们才发现，这些系统更强大，比自洽更重要的是开放。


* 周四 [[2022_03_10]] [[Mar 10th, 2022]]
** #今日鸡汤 #周记

抽烟可产生多巴胺，谈恋爱也可以，一根烟所产生的多巴胺最多可维持个 2 小时。也就是说一天只需 12 根烟，你就不需要爱情！

** #今日文章 #周记

《关于人性》

西汉时有个贪官，因为拍皇帝马屁拍
得好，平步青云，官至宰相后被封侯，划分自家土地时利用手中权力，多占用农民四万多亩。

可偏偏就是这样一个人，年幼时为了读书凿壁偷光。


* 周五 [[2022_03_11]] [[Mar 11th, 2022]]
** #今日鸡汤 #周记 #聊天模板

怎么不聊了？周三了忏悔了？又要努力给资本家吸血了？贱不贱啊？什么时候能站起来啊？都把手机掏出来！聊他妈的！做新时代的主人！做领导的爹！ 我觉得有些群员心态还是没有放稳，现在这么好的带薪聊天机会，不珍惜，你给老板打工搬砖，你能学到东西吗？

** #今日文章 #周记

《法西斯谎言简史》

如果想要了解我们棘手的当下，就需要关注法西斯意识形态家的历史，关注他们的修辞是如何以及为何导致了大屠杀、战争和毁灭。

……，答案是，他们是通过散布意识形态谎言得逞的。

法西斯分子的政治权力在很大程度上源自对真相的收买和对谎言的广泛宣传。


* 周六 [[2022_03_12]] [[Mar 12th, 2022]]
** #今日鸡汤 #周记

中国人从不爱中国人，但却很爱国，爱人是需要投入情感，付出时间、精力、经济成本的，爱国只需付出口水……。 胡适 #名人名言

** #今日文章 #周记

《人为什么要读书》 —— 胡适

从前有一位大哲学家 做了一篇《读书乐》，说到读书的好处，他说：“书中自有千钟粟，书中自有黄金屋，书中自有颜如玉。”这意思就是说，读了书可以做大官，获厚禄，可以不至于住茅草房子，可以娶得年轻的漂亮太太（台下哄笑）。诸位听了笑起来，足见诸位对于这位哲学家所说的话不十分满意，现在我就讲所以要读书的别的原因。

为什么要读书？有三点可以讲：第一，因为书是过去已经知道的知识学问和经验的一种记录，我们读书便是要接受这人类的遗产；第二，为要读书而读书，读了书便可以多读书；第三，读书可以帮助我们解决困难，应付环境，并可获得思想材料的来源。

第一，因为书是代表人类老祖宗传给我们的知识的遗产，我们接受了这遗产，以此为基础，可以继续发扬光大，更在这基础之上，建立更高深更伟大的知识。

如果每样东西，要个个人从头学起，而不去利用过去的知识，那不是太麻烦了吗？所以人有了这知识的遗产，就可以自己去成家立业，就可以缩短工作，使有余力做别的事。

第二点稍复杂，就是为读书而读书。读书不是那么容易的一件事情，不读书不能读书，要能读书才能多读书。

读书固然可以扩充知识，但知识越扩充了，读书的能力也越大，这便是“为读书而读书”的意义。读书的目的在于读书，要读书越多才可以读书越多。

第三点，读书可以帮助解决困难，应付环境，供给思想材料。知识是思想材料的来源。

读书好像用兵，养兵求其能用，否则即使坐拥十万二十万的大兵也没有用处，难道只好等他们“兵变”吗？

至于“读什么书”，我可以很诚恳地说，中国旧籍是经不起读的。希望大家不要怕读书，起初的确要查阅字典，但假使能下一年苦功，继续不断做去，那么，在一二年中定可开辟一个乐园，还只怕求知的欲望太大，来不及读呢。

我总算是老大哥，今天我就根据我过去三十五年读书的经验，给你们这一个临别的忠告。


* 周日 [[2022_03_13]] [[Mar 13th, 2022]]
** #今日鸡汤 #周记

降低离婚率最好方法就是先降低结婚率。 #计划生育

** #今日文章 #周记

《做酸酸，防冠冠》 #疫情

红管管 白签签
排队一起做酸酸
做完酸酸吃饭饭
吃完饭饭等单单
单单出来到时间
继续排队做酸酸
在家呆着防冠冠
没事不能胡转转
胡转可能得冠冠

