#+类型: 2204
#+主页: [[归档202204]]

* 周一 [[2022_04_11]] [[Apr 11th, 2022]]
** #今日鸡汤 #周记

飞行员要求：思想进步、品德优良、遵纪守法、历史清白、现实表现好；拥护党的路线、方针、政策，思想进步，历史清楚，无重大违法违纪问题。

** #今日文章 #周记

《人世间》

“从你出生的那一刻，端什么碗，吃什么饭，经历什么事，什么时候和谁结婚，都是定数，别太难为自己，顺其自然就好。人生的剧本你早在天堂看了，你之所以选择这个剧本，是因为这一生中有你认为值得的地方。”


* 周二 [[2022_04_12]] [[Apr 12th, 2022]]
** #今日鸡汤 #周记

人啊，在哪儿都是混，但千万不要落到那些不如你的人手中。

** #今日文章 #周记

《新华社：一党独裁，遍地是灾》

打开我国的地图，睁开眼睛一看，国民党一党专政下的地区，哪里没有灾荒？单就报纸上发表的材料来看，可以看出灾荒是异常严重的。如湖南、河南、安徽、广东、广西、江苏、湖北、江西、四川，以及陕、甘、青、滇等省，真是遍地是灾，尤其是湖南等地，实在是惨不忍闻。

所以这些救灾的治本办法，只有走上和平、民主的道路时，才能完满解决。

--《新华日报》社论 1946 年 3 月 30 日


* 周三 [[2022_04_13]] [[Apr 13th, 2022]]
** #今日鸡汤 #周记

成熟的表现，有时是对“不成熟”的缺乏耐心。

** #今日文章 #周记

《活在当下》

很多人都以为自己 10 岁的时候不努力，20 岁的时候努力也不晚；很多人都以为自己 20 岁的时候不努力，30 岁的时候努力也不晚；甚至还有人觉得 30 岁的时候不努力，40 岁的时候日子还能越过越好。

他们基本上都是在幻觉中度过自己的一生的。

事实上，人越年轻，努力的效果越加倍，年龄越大，每一步努力极其艰辛。


* 周四 [[2022_04_14]] [[Apr 14th, 2022]]
** #今日鸡汤 #周记

或许不该主动去帮助别人。

** #今日文章 #周记

《男生真的会爱一个女生很久很久吗？》

不会，我老婆 18 年发现宫颈癌晚期，不到三个月就走了，在最后的日子里，我每天都在渴求奇迹的发生，也带着她到北京各大医院治疗，可是她还是离开了我和女儿，离开后的日子一段时间里，我真的无法接受，我不敢回家，家里的每个角落里都有她生活过的痕迹，我以为我这辈子都走不出去了。

可笑的是，19 年春天，老婆离开的第一个春节过后，我又结婚了，家里人介绍的，比我小 10 岁，30 岁出头的年纪，嫁给了我这个没了妻子的人，她年轻漂亮，和我女儿相处的也挺好生活继续着，家里关于我老婆的痕迹慢慢的消失了，我也沉浸在这个圆满的新家庭中。

直到上周，一家人在看月亮，女儿不经意间的说，今天月亮真圆，不知道妈妈在那边看见了没有，我这才意识到，我已经好久没有想起我的老婆了。


* 周五 [[2022_04_15]] [[Apr 8th, 2022]]
** #今日鸡汤 #周记

5

** #今日文章 #周记

5


* 周六 [[2022_04_16]] [[Apr 15th, 2022]]
** #今日鸡汤 #周记

6

** #今日文章 #周记

6


* 周日 [[2022_04_17]] [[Apr 16th, 2022]]
** #今日鸡汤 #周记

7

** #今日文章 #周记

7

