#+类型: 2205
#+主页: [[归档202205]]

* 周三 [[2022_05_18]] [[May 18th, 2022]]
** #今日鸡汤 #周记

即使认为处理某个危机啥都不干就是最好的，公关部门可能也不敢啥都不干。一旦判断失误，事儿大了，你啥都没干，肯定完蛋。而瞎搞一通，搞砸了，领导还可能认为事儿确实很难平，你也努力了。即使没判断失误，啥都不干，事儿真的自己平了，领导也可能想“我要这铁棒有何用”。于是裁你的人，减你的奖金。

** #今日文章 #周记

40 岁以上的人，人生第一次机会在 2008 年，第二次机会在 2019 年，最后一次在 2030 年附近，能够抓住一次你就能够成为中产阶级，这就是人生发财靠康波的道理。

1985 年之后出生的人，第一次人生机会只能在 2019 年出现。


* 周六 [[2022_05_21]] [[May 21st, 2022]]
** #今日鸡汤 #周记

任务一旦确定下来，执行就一定要快。时间不够用，就先快速拿出初版来，之后再进行迭代。

如果一个任务时间卡的不紧，要求不严，就势必产生拖延。一个任务拖拖拉拉，一堆任务前后影响，事情就全都做不成了。

** #今日文章 #周记

1. 很多人谈论爱情常提及“有趣的灵魂”，以彰显对爱的格调与追求。
在我看来“有趣”更像是“取悦他人的能力”。一个人自得其乐，在外人眼中多半毫无魅力可言。地铁中捧书傻笑的人，在路边专注打游戏的人，他们忘我地享受着自己的趣味。

众人渴望有趣的灵魂，无非希望通过他人取悦自己，填补内心的空虚。

2. 当贫帘到一定的程度，就根本没有能力去思考教养、出路、眼界。所谓尊严、志气、骨气、傲气全都消失殆尽。当生存都成为一种奢侈的时候，逆来顺受、苟且偷生就成为非常现实的选择。

—— 使人民贫穷，是国家维持统治的最佳方式。拿最低的工资，买最贵的房子，吃最贵的药，还有五花八门的税收，想不穷都难。


* 周日 [[2022_05_22]] [[May 22nd, 2022]]
** #今日鸡汤 #周记

人与人，往往因为误会而相遇，因为了解而分开。

** #今日文章 #周记

关心经济的岂止老胡!请不要给我戴高帽

关心中国经济的岂止老胡!各地党委政府哪有不关心域内经济的，很多专家更是以论述经济为己长。老胡只是个媒体人，带着自己的敏感，去参与、推动必要的讨论和聚焦。

舆论场抓眼球的规律就是把一个话题绝对化，为了流量，很多人为夸张、强化普通的材料不遗余力。所以图论场上有太多愤怒，惊喜，狠踩和拔高。要说老胡有什么独特之处，可能是我说话一直挺平和的，求中而避免极端。我基本不踩谁不害谁，像老胡这样说话不求激进居然也能保持高流量，可能是幸运吧。

现在经常有人把老胡当一个话题“蹭”流量，他们未必都是恶意，一些人借说老胡，抒发自己的主张和焦虑，挂上“胡锡进”，为的是吸引更多阅读。老胡既然成了网上公众人物，自然有任人评说的思想准备，并愿意把我的账号流量为大家共享。

但希望评论者尊重基本事实，不要给老胡制造吓人的罪名，也别给我戴什么高帽。像说“除了胡锡进，没人关心经济了"，明显是夸张之论，甚至是瞎说。这种宣扬对很多人不公!我认为，一个人要表达自己的看法，哪怕想迫流量，也不该做这样不符合事实的耸动评判。

老胡就是个普通的媒体人，在履行作为流量“大V”的社会责任，公众关注的话题，我自有不沉默的义务。我也对社会持续包容我充满信心，我从不觉得自己说话是冒了多大风险。在这当中，我个人的羽毛尤其不重要，我愿意并且相信，我作为一名党的新闻工作老注定与绝大多数党的和极分子一样，与党的事业，与这个时代任务和使命共英辰

