#+类型: 2204
#+主页: [[归档202204]]

* 周一 [[2022_04_04]] [[Apr 4th, 2022]]
** #今日鸡汤 #周记 #程序员 #人生


如果你不知道如何开始你的设计（不管是什么设计），我倒是有一个通用的方法，简单描述如下： 

目的 -> 流程 -> 成分 -> 关系 -> 平衡。

** #今日文章 #周记

《结婚的意义》

结婚的意义是什么？

这是我听到非常喜欢的答案 —— 结婚是为了：

一个相爱相知相伴的人在生活中能给你勇气；

遇到事能有个人商量；

在生活累的时候彼此相互安慰鼓励；

在外受了委屈回到家有个温暖的拥抱。

我开着车，你坐在副驾驶车里放着我们相互听的音乐一起下班回家浪漫、吃饭。

愿你此生 终得一人	
暖你心窝 伴你终老


* 周二 [[2022_04_05]] [[Apr 5th, 2022]]
** #今日鸡汤 #周记 #上海疫情

大会上的讲话(要点：)
上海的错误不在于探索新的防疫方法，这种探索是值得肯定和鼓励的。

上海的错误在于没有底线思维，没有划清底线，没有为底线突破以后做足够的准备，结果就是破防了不愿承认，爆发了没有准备，各种资源被刺穿，应检尽检应收尽收做不到了还在硬杠，总之一句话，丢掉了党的实事求是的原则。


** #今日文章 #周记 #疫情

《辉瑞》

辉瑞的新冠特效药，确实有点贵，但并非贵的离谱。

注意：这种药只需服用 5 天，一疗程正好 1 盒的量。

不是是这药一盒 2300，得吃好几盒。而是一盒 2300，吃一盒就够了。

一个患者 2300 元，还是贵，能降到 200 左右最合适。

这种可能性很大，新冠国产灭活疫苗早期采购价是 200，现在不到 20。量上去了，价就能下来。

至于说这药应该自费的，我就纳闷了：这款药物能降低 88% 的重症风险，改成自费的话，谁舍不得这 2300？是有钱人还是穷人？

大概只有最贫困的那部分中国老百姓，才会舍不得吃这药。

让这药自费，是觉得穷人该死吗？


* 周三 [[2022_04_06]] [[Apr 6th, 2022]]
** #今日鸡汤 #周记

世界上现在有三种抗疫模式：中国式清零；国外的躺平；上海的仰卧起坐，本来上海要躺平了，被全国人民扶起来了。

** #今日文章 #周记

《无题》

丈夫要求自己和妻子一起隔离。当然不被允许。

为此，丈夫组织了在护理中心的全部家属占领了一个房间，把门从内堵死。坚决拒绝离开护理中心。

警察来了。攻进了他们的房间。以破坏抗疫的理由抓走该丈夫。

为了安抚这些家属，护理中心许诺会另外安排护理人员。实际是一个护理人员要管十几个病人。而负责这个妻子的人，并不会吸痰。
结果，自然就是必然的结果了。

仅仅一天后，因为妻子没有语言能力，无法呼救，也没有人给她吸痰，痰堵在气管里，相信是经过相当长意识清醒下的挣扎后，窒息死亡。

给家属的，只是一个通知:死亡并已经火化。连遗体都看不到。


* 周四 [[2022_04_07]] [[Apr 7th, 2022]]
** #今日鸡汤 #周记 #人生

规矩，从来就是给守规矩的人制定的，有关系有权利，一直都是特殊群体。 

** #今日文章 #周记

《你知道什么是 PUA 吗》

“你太胖了”，这是批评。

“你太胖了，去减肥吧”，这是批评+建议。

“你太胖了，别人都讨厌你，只有我不讨厌你，不嫌弃你，明白吗？”“别人都觉得你不好，只有我不嫌弃你所以你要听我的，以后要报答我。这是典型的 PUA，也是精神控制。

相信自己，你很优秀！


* 周五 [[2022_04_08]] [[Apr 8th, 2022]]
** #今日鸡汤 #周记 #人生 #读书与思考

谢晋导演在《芙蓉镇》里已经表达了中国人的最终宿命 —— 活下去，像牲口一样活下去。

** #今日文章 #周记 #疫情

《疫情之下，普通人能干什么？》

第一，如果可能，尽量如实表达痛苦。

第二，如果不敢表达，起码不要美化痛苦。

第三，自己没有原地饿死或家破人亡倒大霉，不代表别人的哀嚎和求助是假的，要对同胞的不幸遭遇抱有起码的同情和悲悯。

第四，如果有余力，尽量为有困难的人提供帮助，哪怕只是声援。

第五，如果连声援也不敢，起码不要去堵别人在绝望中呼救的嘴。

第六，把家里的电视砸了吧。

第十，如果舍不得砸，尽量不要开机。

第八，天下无不散的筵席，道不同，不相为谋，该绝交的就绝交吧。

第九，不要充当人肉喇叭、爪牙和鹰犬。

第十，无论如何，活下去。


* 周六 [[2022_04_09]] [[Apr 9th, 2022]]
** #今日鸡汤 #周记

大佬的略知一二：虽然我对这个领域有研究，但算不上权威，有很多比我强的专家。

我的略知一二：对这个领域根本不懂，虽然门都没摸着，但是在微博上看别人聊过。

** #今日文章 #周记

《上海市委网信办：进一步查处网络圈群造谣行为》

上海市互联网信息办公室在此提醒社交媒体群组的群主、群组成员，在网络上的任何行为都应遵纪守法，当前形势下尤其要防止传播各类谣言和不实信息、散布恐慌情绪，更不得编造谣言、惹是生非、哗众取宠。互联网不是法外之地，更不应是谣言散布的温床。上海市互联网信息办公室将继续根据群众举报和网络巡查，及时对各类谣言进行辟谣澄清，并联合公安等部门对谣言制造者、蓄意传播谣言者一追到底、依法惩处。同时，对于一些恶意传播谣言的群组也将依法作出处理。

上海市互联网信息办公室呼吁：请广大市民从我做起，增强辨别网络谣言能力，主动拒绝传播谣言，共同维护健康有序清朗的网络空间。同时，再次正告极少数谣言制造者“手指动一动，圈群造谣言”的行为违法违规，必将受到法律惩处和社会谴责。

上海市互联网信息办公室

2022年4月8日


* 周日 [[2022_04_10]] [[Apr 10th, 2022]]
** #今日鸡汤 #周记

余华在《活着》里有一段话：永远不要相信苦难是值得的！苦难就是苦难，苦难不会带来成功。苦难不值得追求。磨练意志是因为苦难无法躲避开。

** #今日文章 #周记 #巨婴

《哲学家们都干了些什么》

中国人很狡猾，遇到好事的时候就不说是“命”了，男女相聚，说的是“缘”。缘是什么？佛教概念里讲的是因果报应。

遇到好事讲“缘”，意思就是说这是因为我之前做过什么好事，这是我应得的。但自己遇到坏事就像前面说的，不讲因果改讲宿命论。但等到讨厌的人遇到坏事呢，就又是因果了，骂人家这是“报应”，这是“活该”。那么，要是自己讨厌的人遇到好事了。中国人怎么办呢？多半心中暗骂：某某某你等着，三十年河东三十年河西，谁笑到最后谁笑得最好 —— 他又开始讲辩证法了！

