#+类型: 2202
#+主页: [[归档202202]]

* [[2022_02_17]] [[Feb 17th, 2022]]
** #今日鸡汤 #周记
灵感总是稍纵即逝，你看，我就忘了早晨想说的一句话。
** #今日文章 #周记

《爱》

这是真的。

有个村庄的小康之家的女孩子，生得美，有许多人来做媒，但都没有说成。那年她不过十五六岁吧，是春天的晚上，她立在后门口，手扶着桃树。她记得她穿的是一件月白的衫子。对门住的年轻人同她见过面，可是从来没有打过招呼的，他走了过来。离得不远，站定了，轻轻的说了一声：“噢，你也在这里吗？”她没有说什么，他也没有再说什么，站了一会，各自走开了。

就这样就完了。

后来这女人被亲眷拐子卖到他乡外县去作妻，又几次三番地被转卖，经过无数的惊险的风波，老了的时候她还记得从前那一回事，常常说起，在那春天的晚上，在后门口的桃树下，那年轻人。

于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里，没有早一步，也没有晚一步，刚巧赶上了，那也没有别的话可说，惟有轻轻地问一声：“噢，你也在这里吗？”

（原刊 1944 年 4 月《杂志》月刊第 13 卷第 1 期）


* [[2022_02_18]] [[Feb 18th, 2022]]
** #今日鸡汤 #周记

多交点税并不可以充值智商。

** #今日文章 #周记

《暴君的臣民》

从前看见清朝几件重案的记载，“臣工”〔2〕拟罪很严重，“圣上”常常减轻，便心里想：大约因为要博仁厚的美名，所以玩这些花样罢了。后来细想，殊不尽然。

暴君治下的臣民，大抵比暴君更暴﹔暴君的暴政，时常还不能餍足暴君治下的臣民的欲望。

中国不要提了罢。在外国举一个例：小事件则如 Gogol 的剧本《按察使》〔3〕，众人都禁止他，俄皇却准开演﹔大事件则如巡抚想放耶稣，众人却要求将他钉上十字架〔4〕。

暴君的臣民，只愿暴政暴在他人的头上，他却看着高兴，拿“残酷”做娱乐，拿“他人的苦”做赏玩，做慰安。

自己的本领只是“幸免”。

从“幸免”里又选出牺牲，供给暴君治下的臣民的渴血的欲望，但谁也不明白。死的说“阿呀”，活的高兴着。


* [[2022_02_19]] [[Feb 19th, 2022]]
** #今日鸡汤 #周记

小时候我们词不达意，长大了我们言不由衷，年老了我们欲言又止。

** #今日文章 #周记

《一个人能无耻、愚昧到什么地步？》

昨晚赴一场饭局，和一位权叔聊到人口拐卖。

叔叔是警察，他说，十几年前，他救出过一个被拐卖到深山里的女孩。

女孩是北京某大学的学生，因为交友不慎，不幸被拐卖进西北某穷乡僻壤之地。熟人作案，防不胜防。

买女孩的那户人家特别穷，家里有两个儿子，但只买的起一个媳妇，所以，一女事二夫，晚上轮流伺候。哥哥三十五岁，弟弟三十一岁。

刚拐进来的时候，女孩反抗情绪很大，俩兄弟心软不愿打她，所以便治不住她。村民们便都笑俩兄弟是软蛋，连婆娘都管不住，还帮着出招，怂煎俩兄弟打她，扇她，再不听话就让她睡猪圈。俩兄弟听着学着，心也就狠了。

女孩每天要做不少杂活，如果活干的不好，上去就是一顿拳打脚踢，一天内不许吃饭，要是敢反抗，直接拿烟头烫。

女孩逃跑过两次，都没成功，怕女孩再跑，这户人家就生生把女孩右腿打折了。全村人都看着她不让她跑。

后来，叔叔去救这个女孩的时候，警车差点被这群村民砸成稀巴烂。几个老太婆干脆躺在路上，哭喊着：“你要把人带走，先从我身上辗过去。"

而俩兄弟被逮捕后，对着女孩破口大骂："我买你真是倒了八辈子血霉，你来我家两年，连个娃娃都没怀上，狗x的还把敢警察叫来。你就是跑出去，你也是个被两个男人搞过的 x 婆娘，你看哪个男人会要你！"

至于那些村民们，则纷纷咒骂这个女孩忘恩负义，恩将仇报，俩兄弟给她吃给她穿，连娃娃都没生居然就要跑，还让俩兄弟坐了牢，哭天喊地地骂"人心坏了”。

这并非一个人的无耻，而是一群人的无耻。而无耻之余，更多的是愚昧和无知。可恨，可怜、可悲。愿惨案不再发生。


* [[2022_02_20]] [[Feb 20th, 2022]]
** #今日鸡汤 #周记

你干好了，遭人忌妒；你做得差，让别人看不起；你开放点吧，人家说你骚；保守了，人家说你装；你待人好，人家说你傻；精明一点，人家说你奸；热情了，人家说你浪；冷淡了，人家说你傲。
你就是再好，也有人挑你的刺，对吧？

** #今日文章 #周记

《我们的双生日—赠冬秀》

（民国）九年十二月十七日，即阴历十月初八日，是我的阳历生日，又是冬秀的阴历生日。

他干涉我病里读书，
常说：“你又不要命了！”
我也恼他干涉我，
常说：“你闹，我更要病了！”

我们常常这样吵嘴 ——
每回吵过也就好了。
今天是我们的双生日，
我们订约今天不许吵了！

我可忍不住要做一首生日诗，
他喊道：“哼哼！又做什么诗了？”
要不是我抢的快，
这首诗早被他撕了。
